version: '3'
services:
    webdav:
        image: bytemark/webdav
        restart: always
        ports:
            - "8081:80"
        environment:
            AUTH_TYPE: Digest
            USERNAME: frodo
            PASSWORD: bolson
            LOCATION: /webdav
        volumes:
            - /srv/dav:/var/lib/dav

    reverseproxy:
        image: scheele/reverseproxy
        ports:
          - 82:8081
        restart: always

    nginx:
        depends_on:
          - reverseproxy
        image: nginx:alpine
        restart: always
